version: "2"
services:
  hw:
    image: haydenwade/hayden-wade-dot-com:latest
    restart: always
    ports:
      - 3000:80
  zpo:
    image: haydenwade/zero-plus-one-podcast:latest
    restart: always
    ports:
      - 3001:80
  wawe:
    image: haydenwade/team-wawe:latest
    restart: always
    ports:
      - 3002:80
